QualiSystems/Azure-Shell

.travis.yml, external_requirements.txt, runtests.py, test_requirements.txt
added travis config
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/13)
=> add .travis.yml

package/cloudshell/cp/azure/azure_shell.py, package/cloudshell/cp/azure/domain/services/virtual_machine_service.py, package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, package/tests/test_services/test_services.py
Added the instance type selection and more tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/41)
=> Feature/deploy app #3 gil

drivers/azure_shell/driver.py, package/cloudshell/cp/azure/azure_shell.py, package/cloudshell/cp/azure/domain/services/parsers/azure_model_parser.py, package/cloudshell/cp/azure/domain/services/virtual_machine_service.py, package/cloudshell/cp/azure/domain/vm_management/operations/power_operation.py, package/tests/test_operations/test_power_operation.py, package/tests/test_services/test_services.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/46)
=> Task 5 Power On/Off commands on Azure VM

QualiConf.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/47)
=> added QualiConf.ini

QualiConf.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/48)
=> Changed attributes

package/MANIFEST.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/51)
=> Added MANIFEST file  (not The Communist Manifesto)

package/cloudshell/cp/azure/domain/services/network_service.py, package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, package/tests/test_services/test_services.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/55)
=> task 39 Public IP in Azure

drivers/azure_shell/driver.py, package/cloudshell/cp/azure/azure_shell.py, package/cloudshell/cp/azure/domain/services/parsers/azure_model_parser.py, package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, package/cloudshell/cp/azure/domain/vm_management/operations/refresh_ip_operation.py, package/tests/test_operations/test_deploy_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/64)
=> Task 26 Refresh IP Command

drivers/azure_shell/requirements.txt, external_requirements.txt, package/cloudshell/cp/azure/domain/services/key_pair.py, package/cloudshell/cp/azure/domain/services/storage_service.py, package/cloudshell/cp/azure/models/ssh_key.py, package/tests/test_services/test_services.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/67)
=> task 56 Generate OpenSSH key pair

package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/68)
=> bug 52 same storage name in different reservations

package/cloudshell/cp/azure/domain/vm_management/operations/prepare_connectivity_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/77)
=> added the creation of the key pair to the prepare_connectivity_operation

drivers/azure_shellPackage/Configuration/shellconfig.xml, drivers/azure_shellPackage/DataModel/datamodel.xml, package/cloudshell/cp/azure/domain/services/parsers/azure_model_parser.py, package/cloudshell/cp/azure/models/azure_cloud_provider_resource_model.py
@GilGald for task 12 "Prepare connectivity"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/81)
=> Cloud Provider management_group_name added

drivers/azure_shell/driver.py, drivers/deployment_drivers/azure_vm/driver.py, package/cloudshell/cp/azure/azure_shell.py, package/cloudshell/cp/azure/domain/services/storage_service.py, package/cloudshell/cp/azure/domain/vm_management/operations/prepare_connectivity_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/83)
=> added ErrorHandlingContext to deployment driver

package/tests/test_operations/test_delete_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/87)
=> delete_operation exceptions tests added

package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, package/tests/test_operations/test_deploy_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/88)
=> Added tests to deploy operation

package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/91)
=> fix get virtual network in deploy operation

package/tests/test_connectivity/test_cleanup_connectivity.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/95)
=> Test cleanup connectivity test added.

package/cloudshell/cp/azure/domain/vm_management/operations/prepare_connectivity_operation.py, package/tests/test_operations/test_prepare_connectivity.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/96)
=> added added more tests

package/cloudshell/cp/azure/domain/services/network_service.py, package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, package/tests/test_operations/test_deploy_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/86)
=> Bug 85 When app is deployed it get his public IP as his address

package/cloudshell/cp/azure/domain/services/virtual_machine_service.py, package/tests/test_operations/test_delete_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/102)
=> virtual_machine_service.py tests added

.coveragerc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/103)
=> models (no logic at all) excluded from coverage

package/cloudshell/cp/azure/domain/vm_management/operations/prepare_connectivity_operation.py, package/tests/test_operations/test_prepare_connectivity.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/104)
=> fix cidr bug

.coveragerc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/105)
=> Ops fix :)

.coveragerc, package/tests/test_services/test_services.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/107)
=> no models check

package/tests/test_services/test_services.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/120)
=> storage_service.py coverage

package/tests/test_services/test_services.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/124)
=> added test_create_virtual_network

package/tests/test_operations/test_delete_operation.py, package/tests/test_operations/test_deploy_operation.py, package/tests/test_services/test_services.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/125)
=> self.network_service.get_public_ip

package/tests/test_cp/test_azure/test_domain/test_services/test_parsers/test_rules_attribute_parser.py
add unittests for:
- cloudshell.cp.azure.domain.services.parsers.rules_attribute_parser
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/128)
=> increase unit tests coverage

.coveragerc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/129)
=> Ignore tests

.coveragerc, package/cloudshell/cp/azure/domain/vm_management/operations/prepare_connectivity_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/130)
=> fixed bug with results

package/cloudshell/cp/azure/domain/vm_management/operations/prepare_connectivity_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/132)
=> send result fix bug 2

package/tests/test_operations/test_prepare_connectivity.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/139)
=> updated tests

package/cloudshell/cp/azure/azure_shell.py, package/cloudshell/cp/azure/domain/vm_management/operations/delete_operation.py, package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, package/cloudshell/cp/azure/domain/vm_management/operations/power_operation.py, package/cloudshell/cp/azure/domain/vm_management/operations/prepare_connectivity_operation.py, package/cloudshell/cp/azure/domain/vm_management/operations/refresh_ip_operation.py, package/tests/test_connectivity/test_cleanup_connectivity.py, package/tests/test_cp/test_azure/test_azure_shell.py, package/tests/test_cp/test_azure/test_domain/test_vm_management/test_operations/test_refresh_ip_operation.py, package/tests/test_operations/test_delete_operation.py, package/tests/test_operations/test_deploy_operation.py, package/tests/test_operations/test_power_operation.py, package/tests/test_operations/test_prepare_connectivity.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/140)
=> Task 100 refactor azure_shell.py

drivers/azure_shell/driver.py, package/cloudshell/cp/azure/domain/vm_management/operations/prepare_connectivity_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/166)
=> fixed bug #152 - added lock on subnet create in prepare connectivity operation

drivers/azure_shell_specs/deploy_vm.ini, drivers/azure_shell_specs/deploy_vm_from_custom_image.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/180)
=> fix slash bug

package/cloudshell/cp/azure/domain/vm_management/operations/prepare_connectivity_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/194)
=> fix asycn NSG rules creation bug in prepare_connectivity operation

run_packager.bat
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/195)
=> added run_packager.bat

package/cloudshell/cp/azure/domain/vm_management/operations/prepare_connectivity_operation.py, package/tests/test_cp/test_azure/test_domain/test_vm_management/test_operations/test_prepare_connectivity.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/209)
=> Prepare connectivity fix.

package/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/213)
=> fix package requirements (adding requests==2.11.1)

package/cloudshell/cp/azure/azure_shell.py, package/cloudshell/cp/azure/domain/services/parsers/azure_resource_id_parser.py, package/cloudshell/cp/azure/domain/vm_management/operations/refresh_ip_operation.py, package/tests/test_cp/test_azure/test_domain/test_services/test_parsers/test_azure_resource_id_parser.py, package/tests/test_cp/test_azure/test_domain/test_vm_management/test_operations/test_refresh_ip_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/207)
=> bug 186 Refresh IP On Public IP

package/cloudshell/cp/azure/domain/services/parsers/rules_attribute_parser.py, package/tests/test_cp/test_azure/test_domain/test_services/test_parsers/test_rules_attribute_parser.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/214)
=> fix bug 202 NSG: inbound port rule only works with lower case

package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, package/tests/test_cp/test_azure/test_domain/test_vm_management/test_operations/test_deploy_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/215)
=> bug 203 inbound port is still active when there is no public IP

.travis.yml, drivers/azure_shell/requirements.txt, drivers/deployment_drivers/azure_vm/requirements.txt, drivers/deployment_drivers/azure_vm_from_custom_image/requirements.txt, package/cloudshell/cp/azure/domain/services/cryptography_service.py, package/cloudshell/cp/azure/domain/vm_management/operations/prepare_connectivity_operation.py, package/requirements.txt
- fixing cryptography_service unbound method error
- improved error logging
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/224)
=> fixing cryptography_service unbound method error

package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, package/tests/test_cp/test_azure/test_domain/test_vm_management/test_operations/test_deploy_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/226)
=> bug 200 failed to deploy app when app name is longer than 8 characters

package/cloudshell/cp/azure/azure_shell.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/230)
=> add loggs for starting/ending command operations

package/cloudshell/cp/azure/azure_shell.py, package/cloudshell/cp/azure/domain/services/name_provider.py, package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, package/cloudshell/cp/azure/domain/vm_management/operations/prepare_connectivity_operation.py, package/tests/test_cp/test_azure/test_domain/test_vm_management/test_operations/test_deploy_operation.py, package/tests/test_cp/test_azure/test_domain/test_vm_management/test_operations/test_prepare_connectivity.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/231)
=> task 188 Refactor name creation in azure shell

package/cloudshell/cp/azure/domain/services/network_service.py, package/cloudshell/cp/azure/domain/services/security_group.py, package/cloudshell/cp/azure/domain/services/storage_service.py, package/cloudshell/cp/azure/domain/services/virtual_machine_service.py, package/cloudshell/cp/azure/domain/vm_management/operations/access_key_operation.py, package/cloudshell/cp/azure/domain/vm_management/operations/delete_operation.py, package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, package/cloudshell/cp/azure/domain/vm_management/operations/power_operation.py, package/cloudshell/cp/azure/domain/vm_management/operations/prepare_connectivity_operation.py, package/cloudshell/cp/azure/domain/vm_management/operations/refresh_ip_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/216)
=> task 205 move the @retry decorator to the domains services

package/cloudshell/cp/azure/domain/vm_management/operations/delete_operation.py, package/tests/test_services/test_services.py
Lock added for updating subnet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/235)
=> Teardown concurrency bug 190

package/cloudshell/cp/azure/domain/vm_management/operations/prepare_connectivity_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/236)
=> Update prepare_connectivity_operation.py traceback ref

package/cloudshell/cp/azure/azure_shell.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/243)
=> GetAccesskey fix

package/cloudshell/cp/azure/azure_shell.py, package/cloudshell/cp/azure/domain/services/storage_service.py, package/cloudshell/cp/azure/domain/vm_management/operations/delete_operation.py, package/tests/test_connectivity/test_cleanup_connectivity.py, package/tests/test_cp/test_azure/test_azure_shell.py, package/tests/test_cp/test_azure/test_domain/test_vm_management/test_operations/test_delete_operation.py, package/tests/test_services/test_services.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/239)
=> task 65 Deleting VM its data disks should be deleted

package/cloudshell/cp/azure/domain/vm_management/operations/delete_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/254)
=> added more logs

package/cloudshell/cp/azure/domain/services/virtual_machine_service.py, package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, package/tests/test_cp/test_azure/test_domain/test_services/test_virtual_machine_service.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/265)
=> fix bug 264 Custom Image Credentials

package/tests/test_cp/test_azure/test_domain/test_services/test_generic_lock_provider.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/277)
=> Added another test ,testing the deletion of the lock object

drivers/azure_shellPackage/DataModel/datamodel.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/281)
=> fix bug 270 Description Error: Image OS Type

package/cloudshell/cp/azure/azure_shell.py, package/cloudshell/cp/azure/domain/services/lock_service.py, package/cloudshell/cp/azure/domain/services/security_group.py, package/cloudshell/cp/azure/domain/vm_management/operations/delete_operation.py, package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, package/cloudshell/cp/azure/domain/vm_management/operations/prepare_connectivity_operation.py, package/tests/test_cp/test_azure/test_domain/test_services/test_security_group.py, package/tests/test_cp/test_azure/test_domain/test_vm_management/test_operations/test_delete_operation.py, package/tests/test_cp/test_azure/test_domain/test_vm_management/test_operations/test_prepare_connectivity.py
- changed subnet locker to be shared between all relevant operations.
- added generic locker on nsg security rule delete
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/290)
=> fixing lockers usage

package/cloudshell/cp/azure/domain/services/security_group.py
So that 2 VM's from 2 different sandboxes wont be able talk with each other
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/293)
=> when rule is created adding the tag Internet on it.

package/cloudshell/cp/azure/domain/vm_management/operations/delete_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/298)
=> fix bug 65 deleting VM its data disks should be delete

drivers/azure_shellPackage/Configuration/shellconfig.xml, drivers/azure_shellPackage/DataModel/datamodel.xml, package/cloudshell/cp/azure/domain/services/parsers/azure_model_parser.py, package/tests/test_cp/test_azure/test_domain/test_services/test_parsers/test_azure_model_parser.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/297)
=> tasks 258, 259, 262 fix datamodel attributes descriptions

drivers/azure_shellPackage/DataModel/datamodel.xml, package/cloudshell/cp/azure/domain/services/parsers/rules_attribute_parser.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/320)
=> updated vm size description and fixed some doc strings

deployment_templates/guacamole-quali-install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/324)
=> added command to complete all pending yum transactions

package/cloudshell/cp/azure/azure_shell.py, package/cloudshell/cp/azure/common/helpers/url_helper.py, package/cloudshell/cp/azure/domain/services/vm_extension.py, package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, package/requirements.txt, package/tests/test_cp/test_azure/test_domain/test_services/test_vm_extension.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/344)
=> Added check if the URL is valid

package/cloudshell/cp/azure/azure_shell.py, package/cloudshell/cp/azure/domain/services/image_data.py, package/cloudshell/cp/azure/domain/services/network_service.py, package/cloudshell/cp/azure/domain/services/tags.py, package/cloudshell/cp/azure/domain/services/virtual_machine_service.py, package/cloudshell/cp/azure/domain/services/vm_credentials_service.py, package/cloudshell/cp/azure/domain/services/vm_extension.py, package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, package/cloudshell/cp/azure/models/deploy_result_model.py, package/cloudshell/cp/azure/models/image_data.py, package/tests/test_cp/test_azure/test_azure_shell.py, package/tests/test_cp/test_azure/test_domain/test_services/test_image_data_factory.py, package/tests/test_cp/test_azure/test_domain/test_services/test_virtual_machine_service.py, package/tests/test_cp/test_azure/test_domain/test_vm_management/test_operations/test_deploy_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/345)
=> Feature/alex refactor deploy operation + fix bug #287

drivers/azure_shellPackage/DataModel/datamodel.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/377)
=> Updated public IP type description.

package/cloudshell/cp/azure/domain/vm_management/operations/autoload_operation.py, package/tests/test_cp/test_azure/test_domain/test_vm_management/test_operations/test_autoload_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/376)
=> fix bug 363 error message from driver not self explaining enough

deployment_templates/cloudshell_es_install_script.sh, deployment_templates/guacamole-quali-install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/375)
=> fix bug 356 ARM template fails during installing of es & qx scripts

drivers/azure_shellPackage/DataModel/datamodel.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/379)
=> Removed cloud provider

package/cloudshell/cp/azure/common/converters/resource_context.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/391)
=> Added fix to CloudProvider

.travis.yml, drivers/azure_shell/requirements.txt, drivers/deployment_drivers/azure_vm/requirements.txt, drivers/deployment_drivers/azure_vm_from_custom_image/requirements.txt, install_dependencies.sh, package/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/403)
=> updated shell-core requirements version to 3.1

deployment_templates/main_template.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/408)
=> fix bug 393 Azure Template SSH user and password description

drivers/azure_shellPackage/DataModel/datamodel.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/410)
=> fix bug 395 update 'Additional NSG configuration' description

drivers/azure_shellPackage/Configuration/shellconfig.xml, drivers/azure_shellPackage/DataModel/datamodel.xml, package/cloudshell/cp/azure/common/azure_clients.py, package/cloudshell/cp/azure/domain/services/parsers/azure_model_parser.py, package/cloudshell/cp/azure/models/azure_cloud_provider_resource_model.py, package/tests/test_cp/test_azure/test_common/test_azure_clients.py, package/tests/test_cp/test_azure/test_domain/test_services/test_parsers/test_azure_model_parser.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/409)
=> fix bug 387 Rename client Id & Azure Secret

package/cloudshell/cp/azure/domain/vm_management/operations/prepare_connectivity_operation.py, package/tests/test_cp/test_azure/test_domain/test_vm_management/test_operations/test_prepare_connectivity.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/417)
=> fixed storage account name and added unit test

package/cloudshell/cp/azure/domain/vm_management/operations/prepare_connectivity_operation.py, package/tests/test_cp/test_azure/test_domain/test_vm_management/test_operations/test_prepare_connectivity.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/418)
=> fixing storage account name generation

drivers/azure_shellPackage/DataModel/datamodel.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/422)
=> fix descriptions

deployment_templates/cloudshell_es_install_script.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/433)
=> enable supervisord.service in systemctl in ES installation script

package/cloudshell/cp/azure/common/parsers/rules_attribute_parser.py, package/tests/test_cp/test_azure/test_domain/test_services/test_parsers/test_rules_attribute_parser.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/438)
=> fixed inbound ports rules parser for extra delimiters

deployment_templates/cloudshell_es_install_script.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/439)
=> Removed strip of es file in Azure template ES installation script

drivers/azure_shellPackage/DataModel/datamodel.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/450)
=> installation-removal

drivers/azure_shellPackage/DataModel/datamodel.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/461)
=> adding description

package/cloudshell/cp/azure/domain/services/virtual_machine_service.py, package/tests/test_cp/test_azure/test_domain/test_services/test_virtual_machine_service.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/462)
=> disable vm boot diagnostic explicitly for marketplace and custom vms

deployment_templates/guacamole-quali-install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/464)
=> updated script

drivers/azure_shellPackage/DataModel/datamodel.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/468)
=> fixing datamodel

drivers/azure_shell/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/471)
=> updated requirements.txt

package/cloudshell/cp/azure/common/parsers/azure_model_parser.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/472)
=> Fix bug boolean didnt convert

package/cloudshell/cp/azure/common/parsers/azure_model_parser.py, package/cloudshell/cp/azure/common/parsers/resource_context.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/478)
=> added support for 2nd gen attributes without namespace

drivers/azure_shellPackage/DataModel/datamodel.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/479)
=> Removed searchable flag from CLP family

drivers/azure_shell/requirements.txt, install_dependencies.sh, package/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/483)
=> updated to latest 8.2 cloudshell automation api

deployment_templates/main_template.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/488)
=> updated url for the executions server installer

drivers/azure_shell/driver.py, drivers/azure_shell/drivermetadata.xml, drivers/azure_shell/requirements.txt, package/cloudshell/cp/azure/azure_shell.py, package/cloudshell/cp/azure/domain/common/vm_details_provider.py, package/cloudshell/cp/azure/domain/vm_management/operations/vm_details_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/490)
=> Get VM Details supports bulk requests now.

drivers/azure_shell/requirements.txt
Version updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/491)
=> Igor 164544 vm details

drivers/azure_shell/requirements.txt, external_requirements.txt, package/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/496)
=> added dateutil package to requirements file

external_requirements.txt, package/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/499)
=> removed python-dateutil requirements

deployment_templates/main_template.json, deployment_templates/qxExternalMode.json, deployment_templates/qxInternalMode.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/500)
=> update centos image sku to 7.4

drivers/azure_shellPackage/DataModel/datamodel.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/502)
=> Add EditableOnlyInAppTemplate attribute

drivers/azure_shell/driver.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/507)
=> fixed another import

drivers/azure_shell/driver.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/508)
=> fix spelling mistake

package/cloudshell/cp/azure/domain/vm_management/operations/delete_operation.py, package/tests/test_cp/test_azure/test_domain/test_vm_management/test_operations/test_delete_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/511)
=> add support for multiple subnets in cleanup operation

package/cloudshell/cp/azure/azure_shell.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/518)
=> show application ports for subnets

package/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/522)
=> fixed requirements

drivers/azure_shellPackage/DataModel/datamodel.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/523)
=> Fix Attributes

drivers/azure_shellPackage/DataModel/datamodel.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/524)
=> removed auto power off attribute from datamodel

deployment_templates/main_template.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/530)
=> Adding feature: set custom sandbox vnet parameters

package/cloudshell/cp/azure/domain/services/storage_service.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/535)
=> changed retry max attempts on get storage account key

package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/536)
=> fixed a bug causing deployment without subnet to fail

package/cloudshell/cp/azure/domain/vm_management/operations/PrepareSandboxInfraOperation.py, package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, package/tests/test_cp/test_azure/test_domain/test_vm_management/test_operations/test_deploy_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/539)
=> fix scenario where no subnet specified, and multiple apps

package/cloudshell/cp/azure/azure_shell.py, package/tests/test_cp/test_azure/test_azure_shell.py, package/tests/test_cp/test_azure/test_common/test_vm_details_provider.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/542)
=> fixed tabulation of getapplicationports

package/cloudshell/cp/azure/azure_shell.py, package/cloudshell/cp/azure/common/parsers/azure_model_parser.py, package/tests/test_cp/test_azure/test_azure_shell.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/550)
=> get application ports

package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, package/tests/test_cp/test_azure/test_domain/test_vm_management/test_operations/test_deploy_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/551)
=> reinstated

drivers/azure_shell/driver.py, drivers/azure_shell/drivermetadata.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/552)
=> disabled capability to create routetable, will be added in GA

drivers/azure_shellPackage/DataModel/datamodel.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/553)
=> removed disk size from cloud provider

package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/555)
=> fixed check if there are only private subnets

drivers/azure_shell/drivermetadata.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/562)
=> updated driver version as well

package/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/563)
=> leave msrest as is

package/cloudshell/cp/azure/common/helpers/ip_allocation_helper.py, package/cloudshell/cp/azure/domain/services/network_service.py, package/cloudshell/cp/azure/domain/vm_management/operations/delete_operation.py, package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, package/tests/test_cp/test_azure/test_domain/test_vm_management/test_operations/test_deploy_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/575)
=> changed how we check if static allocation

drivers/azure_shellPackage/Configuration/shellconfig.xml, drivers/azure_shellPackage/DataModel/datamodel.xml, package/cloudshell/cp/azure/common/parsers/azure_model_parser.py, package/cloudshell/cp/azure/models/azure_cloud_provider_resource_model.py
Add "VNET Mode" attribute with values: "Single", "Multiple" and description
Add "VNET CIDR" attribute with description
Add "Custom VNET DNS" attribute with description
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/576)
=> added new attributes:

package/cloudshell/cp/azure/domain/vm_management/operations/autoload_operation.py, package/cloudshell/cp/azure/models/azure_cloud_provider_resource_model.py, package/tests/test_cp/test_azure/test_domain/test_vm_management/test_operations/test_autoload_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/582)
=> Added validations during autoload for new vnet options on CLP

package/cloudshell/cp/azure/domain/vm_management/operations/snapshot_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/585)
=> Multiple vnets disk type

package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/588)
=> vm nsg doesnt have rules when multiple vnets

package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/589)
=> fixed inbound ports

package/cloudshell/cp/azure/domain/vm_management/operations/PrepareSandboxInfraOperation.py, package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/590)
=> fix inbound ports 2

package/cloudshell/cp/azure/domain/vm_management/operations/PrepareSandboxInfraOperation.py, package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/591)
=> do not create a sandbox NSG for the multiple vnet scenario

package/cloudshell/cp/azure/domain/services/network_service.py, package/cloudshell/cp/azure/domain/services/security_group.py, package/cloudshell/cp/azure/domain/vm_management/operations/delete_operation.py, package/tests/test_cp/test_azure/test_domain/test_vm_management/test_operations/test_delete_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/600)
=> when app is manually removed from sandbox, remove its NSG artifacts

package/cloudshell/cp/azure/common/helpers/retrying_helpers.py, package/cloudshell/cp/azure/domain/networking_management/operations/add_route_operation.py, package/cloudshell/cp/azure/domain/services/network_service.py, package/cloudshell/cp/azure/domain/services/virtual_machine_service.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/604)
=> added retry mechanism to cover azure retryableerror

package/cloudshell/cp/azure/domain/services/parsers/connection_params.py
fixed
removed re-initializing custom_attributes
cause it deletes the fix of nahum for <= 9.0 versions in revision 1baaebda621aae991b21a24f52d4ce2f4dacb229
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/609)
=> #39107 ticket

package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, package/cloudshell/cp/azure/models/rule_data.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/627)
=> add port range and protocol to the inbound port rule name

package/cloudshell/cp/azure/domain/vm_management/operations/deploy_operation.py, package/tests/test_cp/test_azure/test_domain/test_vm_management/test_operations/test_deploy_operation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/azure-shell/626)
=> fix issue 625 Remove Inbound ports checks
